### ISSUE TITLE
Unsupported operand types in Guzzle with Laravel Webhook Server

### ISSUE THREAD

**Issue by fhferreira** [spatie/laravel-webhook-server#115]
I am using Laravel-webhook-server at one project with Laravel 6 and php 7.4, and 2 days ago we start to receive this error below:

Symfony\Component\Debug\Exception\FatalThrowableError: Unsupported operand types in /var/www/my-app/vendor/guzzlehttp/guzzle/src/Client.php:310
--

since 2 days ago it call sentry bug tracker with more than 500k events. 

```
Symfony\Component\Debug\Exception\FatalThrowableError: Unsupported operand types in /var/www/my-app/vendor/guzzlehttp/guzzle/src/Client.php:310
Stack trace:
#0 /var/www/my-app/vendor/guzzlehttp/guzzle/src/Client.php(148): GuzzleHttp\Client->prepareDefaults(Array)
#1 /var/www/my-app/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\Client->requestAsync('shouldReport', Array, Array)
#2 /var/www/my-app/vendor/guzzlehttp/guzzle/src/Client.php(95): GuzzleHttp\Client->request('shouldReport', Array, Array)
#3 /var/www/my-app/vendor/guzzlehttp/guzzle/src/Client.php(62): GuzzleHttp\Client->__call('shouldReport', Array)
#4 [internal function]: GuzzleHttp\Client->__construct(Array)
#5 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Container/Container.php(843): ReflectionClass->newInstanceArgs(Array)
#6 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('GuzzleHttp\\Clie...')
#7 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve('GuzzleHttp\\Clie...', Array, true)
#8 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Foundation\Application->resolve('GuzzleHttp\\Clie...', Array)
#9 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\Container\Container->make('GuzzleHttp\\Clie...', Array)
#10 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(120): Illuminate\Foundation\Application->make('GuzzleHttp\\Clie...', Array)
#11 /var/www/my-app/vendor/spatie/laravel-webhook-server/src/CallWebhookJob.php(63): app('GuzzleHttp\\Clie...')
#12 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\WebhookServer\CallWebhookJob->handle()
#13 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#16 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#17 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#18 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Spatie\WebhookServer\CallWebhookJob))
#19 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Spatie\WebhookServer\CallWebhookJob))
#20 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow(Object(Spatie\WebhookServer\CallWebhookJob), false)
#22 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(Spatie\WebhookServer\CallWebhookJob))
#23 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Spatie\WebhookServer\CallWebhookJob))
#24 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\RedisJob), Object(Spatie\WebhookServer\CallWebhookJob))
#26 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#27 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(368): Illuminate\Queue\Jobs\Job->fire()
#28 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#29 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#30 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#31 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#32 /var/www/my-app/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#33 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#34 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#35 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#36 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#37 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#38 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#39 /var/www/my-app/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#40 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#41 /var/www/my-app/vendor/symfony/console/Application.php(1009): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /var/www/my-app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /var/www/my-app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /var/www/my-app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /var/www/my-app/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 {main}
``` 

![image](https://user-images.githubusercontent.com/140686/147417492-3114402f-5249-4410-9c46-9bf5e1983b1a.png)

**Comment by fhferreira** [comment]
@freekmurze any help?

**Comment by fhferreira** [comment]
![image](https://user-images.githubusercontent.com/140686/147839252-0ded9745-94e6-43aa-bb53-72d04d7da8c4.png)

**Comment by fhferreira** [comment]
+1

**Comment by freekmurze** [comment]
Please don't +1 in general, and certainly not your own issue 😅

I'm open for a PR that fixes the issue for you.

**Comment by fhferreira** [comment]
Sure. Tks.
